"""Fix relationship between Category and Product

Revision ID: 0244c4809f88
Revises: 11896d4e2043
Create Date: 2024-06-20 23:39:33.532691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0244c4809f88'
down_revision: Union[str, None] = '11896d4e2043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
